Feature/application form UI
ms-club-sliit/msclubwesite-v2 pull request #28
Opened 2021-11-30 17:44 UTC by isurupathumherath

Updated error validation in Contact form & Created Application Form

2021-11-30 17:47 UTC, rusiruavb commented
@isurupathumherath CI/ CD is failed. Run the build in your local machine and check why it is failing.

2021-12-01 04:44 UTC, rusiruavb requested changes

2021-12-01 04:44 UTC, rusiruavb commented on src/interfaces/JoinUsFormInterface.ts
> +  formErrors: {
No need to have `formErrors` object. Now we use **Yup** package to handle validations. Remove the `formErrors` object and test the feature again.

2021-12-01 04:44 UTC, rusiruavb commented on src/pages/contact/contact-form-section.tsx
>    /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
Remove `emailRegEX` if it is not use.

2021-12-01 04:44 UTC, rusiruavb commented on src/pages/join_us/join-us-form-section.tsx
> +const skillOptions = [
Remove `skillOptions`. Use React select. I will look in to the react select issue

2021-12-01 04:44 UTC, rusiruavb commented on src/pages/join_us/join-us-form-section.tsx
> +const emailRegEX = RegExp(
`emailRegEX` is not used. Remove it.

2021-12-01 04:44 UTC, rusiruavb commented on src/pages/join_us/hero-section.tsx
> +          <img src="/assets/join_us_header.svg" alt="home header" className="contact-us-header-img" />
We need to change the header image for the application.

2021-12-02 10:26 UTC, rusiruavb approved these changes

2021-12-02 10:28 UTC, senuravihanjayadeva approved these changes

2021-12-02 10:28 UTC, merged