Get Webinars from the backend API
ms-club-sliit/msclubwesite-v2 pull request #70
Opened 2022-01-29 15:47 UTC by SasinduNanayakkara

2022-01-29 16:06 UTC, senuravihanjayadeva requested changes

2022-01-29 16:06 UTC, senuravihanjayadeva commented on src/pages/event/past-webina.tsx
> +    .then((data) =>{
change "data" to "response"

2022-01-29 16:06 UTC, senuravihanjayadeva commented on src/pages/event/past-webina.tsx
> +      setWebinarList(data.data);
response.data

2022-01-29 16:06 UTC, senuravihanjayadeva commented on src/pages/event/past-webina.tsx
> +  const [webinarList, setWebinarList] = useState<IWebinar>();
const [webinarList, setWebinarList] = useState<IWebinar[]>([]);

2022-01-29 16:06 UTC, senuravihanjayadeva commented on src/pages/event/past-webina.tsx
> +      {webinarList && webinarList.Items.length > 0 &&
webinarList.Items ?

2022-01-29 16:06 UTC, senuravihanjayadeva commented on src/pages/event/past-webina.tsx
> +          {webinarList.Items.map((event, index) => (
webinarList.Items ?

2022-02-04 08:33 UTC, senuravihanjayadeva approved these changes

2022-02-04 08:38 UTC, miyurugunarathna approved these changes
LGTM

2022-02-04 08:42 UTC, merged