text alignment issue in blog card has been fixed
ms-club-sliit/msclubwesite-v2 pull request #79
Opened 2022-02-07 18:23 UTC by KaveenLaksitha

2022-02-07 19:15 UTC, rusiruavb requested changes
@KaveenLaksitha I have add some comments. Please take a 👀

2022-02-07 19:15 UTC, rusiruavb commented on src/pages/blog/index.tsx
> +      <ScrollToTop smooth style={{marginBottom:60}}/>
Do not create inline styling. Create a separate class and apply it here.

2022-02-07 19:15 UTC, rusiruavb commented on src/pages/board/index.tsx
> +    <ScrollToTop smooth style={{marginBottom:60}}/>
Do not create inline styling. Create a separate class and apply it here.

2022-02-08 05:43 UTC, KaveenLaksitha commented on src/pages/about/index.tsx
> +    <ScrollToTop smooth style={{marginBottom:60}}/>
Component disappears when you add a className property

2022-02-08 14:39 UTC, miyurugunarathna requested changes

2022-02-08 14:39 UTC, miyurugunarathna commented on src/pages/about/index.tsx
> +    <ScrollToTop smooth style={{marginBottom:60}}/>
@KaveenLaksitha I think when you use className property you have to override those styles. Please take a look.
https://github.com/HermanNygaard/react-scroll-to-top/blob/master/src/styles.css
![image](https://user-images.githubusercontent.com/33316556/153009332-63d3707a-61f0-4ccd-9c45-db76e50cbd59.png)

2022-02-08 15:12 UTC, miyurugunarathna approved these changes
LGTM

2022-02-10 02:31 UTC, senuravihanjayadeva approved these changes

2022-02-10 02:32 UTC, merged